<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CidadesSeeder extends Seeder {

    public function run() {

        DB::disableQueryLog();

        $ufs[] = array(
            array("uf" => "AL", "nome" => "AGUA BRANCA"),
            array("uf" => "AL", "nome" => "ALAZAO"),
            array("uf" => "AL", "nome" => "ALECRIM"),
            array("uf" => "AL", "nome" => "ANADIA"),
            array("uf" => "AL", "nome" => "ANEL"),
            array("uf" => "AL", "nome" => "ANUM NOVO"),
            array("uf" => "AL", "nome" => "ANUM VELHO"),
            array("uf" => "AL", "nome" => "ARAPIRACA"),
            array("uf" => "AL", "nome" => "ATALAIA"),
            array("uf" => "AL", "nome" => "BAIXA DA ONCA"),
            array("uf" => "AL", "nome" => "BAIXA DO CAPIM"),
            array("uf" => "AL", "nome" => "BALSAMO"),
            array("uf" => "AL", "nome" => "BANANEIRAS"),
            array("uf" => "AL", "nome" => "BARRA DE SANTO ANTONIO"),
            array("uf" => "AL", "nome" => "BARRA DE SAO MIGUEL"),
            array("uf" => "AL", "nome" => "BARRA DO BONIFACIO"),
            array("uf" => "AL", "nome" => "BARRA GRANDE"),
            array("uf" => "AL", "nome" => "BATALHA"),
            array("uf" => "AL", "nome" => "BATINGAS"),
            array("uf" => "AL", "nome" => "BELEM"),
            array("uf" => "AL", "nome" => "BELO MONTE"),
            array("uf" => "AL", "nome" => "BOA SORTE"),
            array("uf" => "AL", "nome" => "BOA VISTA"),
            array("uf" => "AL", "nome" => "BOA VISTA"),
            array("uf" => "AL", "nome" => "BOCA DA MATA"),
            array("uf" => "AL", "nome" => "BOM JARDIM"),
            array("uf" => "AL", "nome" => "BONIFACIO"),
            array("uf" => "AL", "nome" => "BRANQUINHA"),
            array("uf" => "AL", "nome" => "CACIMBINHAS"),
            array("uf" => "AL", "nome" => "CAJARANA"),
            array("uf" => "AL", "nome" => "CAJUEIRO"),
            array("uf" => "AL", "nome" => "CALDEIROES DE CIMA"),
            array("uf" => "AL", "nome" => "CAMADANTA"),
            array("uf" => "AL", "nome" => "CAMPESTRE"),
            array("uf" => "AL", "nome" => "CAMPO ALEGRE"),
            array("uf" => "AL", "nome" => "CAMPO GRANDE"),
            array("uf" => "AL", "nome" => "CANAA"),
            array("uf" => "AL", "nome" => "CANAFISTULA"),
            array("uf" => "AL", "nome" => "CANAPI"),
            array("uf" => "AL", "nome" => "CANASTRA"),
            array("uf" => "AL", "nome" => "CANGANDU"),
            array("uf" => "AL", "nome" => "CAPELA"),
            array("uf" => "AL", "nome" => "CARNEIROS"),
            array("uf" => "AL", "nome" => "CARRASCO"),
            array("uf" => "AL", "nome" => "CHA PRETA"),
            array("uf" => "AL", "nome" => "COITE DO NOIA"),
            array("uf" => "AL", "nome" => "COLONIA LEOPOLDINA"),
            array("uf" => "AL", "nome" => "COQUEIRO SECO"),
            array("uf" => "AL", "nome" => "CORURIPE"),
            array("uf" => "AL", "nome" => "CORURIPE DA CAL"),
            array("uf" => "AL", "nome" => "CRAIBAS"),
            array("uf" => "AL", "nome" => "DELMIRO GOUVEIA"),
            array("uf" => "AL", "nome" => "DOIS RIACHOS"),
            array("uf" => "AL", "nome" => "ENTREMONTES"),
            array("uf" => "AL", "nome" => "ESTRELA DE ALAGOAS"),
            array("uf" => "AL", "nome" => "FEIRA GRANDE"),
            array("uf" => "AL", "nome" => "FELIZ DESERTO"),
            array("uf" => "AL", "nome" => "FERNAO VELHO"),
            array("uf" => "AL", "nome" => "FLEXEIRAS"),
            array("uf" => "AL", "nome" => "FLORIANO PEIXOTO"),
            array("uf" => "AL", "nome" => "GASPAR"),
            array("uf" => "AL", "nome" => "GIRAU DO PONCIANO"),
            array("uf" => "AL", "nome" => "IBATEGUARA"),
            array("uf" => "AL", "nome" => "IGACI"),
            array("uf" => "AL", "nome" => "IGREJA NOVA"),
            array("uf" => "AL", "nome" => "INHAPI"),
            array("uf" => "AL", "nome" => "JACARE DOS HOMENS"),
            array("uf" => "AL", "nome" => "JACUIPE"),
            array("uf" => "AL", "nome" => "JAPARATINGA"),
            array("uf" => "AL", "nome" => "JARAMATAIA"),
            array("uf" => "AL", "nome" => "JENIPAPO"),
            array("uf" => "AL", "nome" => "JOAQUIM GOMES"),
            array("uf" => "AL", "nome" => "JUNDIA"),
            array("uf" => "AL", "nome" => "JUNQUEIRO"),
            array("uf" => "AL", "nome" => "LAGOA DA AREIA"),
            array("uf" => "AL", "nome" => "LAGOA DA CANOA"),
            array("uf" => "AL", "nome" => "LAGOA DA PEDRA"),
            array("uf" => "AL", "nome" => "LAGOA DANTAS"),
            array("uf" => "AL", "nome" => "LAGOA DO CALDEIRAO"),
            array("uf" => "AL", "nome" => "LAGOA DO CANTO"),
            array("uf" => "AL", "nome" => "LAGOA DO EXU"),
            array("uf" => "AL", "nome" => "LAGOA DO RANCHO"),
            array("uf" => "AL", "nome" => "LAGOA DO RANCHO"),
            array("uf" => "AL", "nome" => "LAJES DO CALDEIRAO"),
            array("uf" => "AL", "nome" => "LARANJAL"),
            array("uf" => "AL", "nome" => "LIMOEIRO DE ANADIA"),
            array("uf" => "AL", "nome" => "MACEIO"),
            array("uf" => "AL", "nome" => "MAJOR ISIDORO"),
            array("uf" => "AL", "nome" => "MAR VERMELHO"),
            array("uf" => "AL", "nome" => "MARAGOGI"),
            array("uf" => "AL", "nome" => "MARAVILHA"),
            array("uf" => "AL", "nome" => "MARECHAL DEODORO"),
            array("uf" => "AL", "nome" => "MARIBONDO"),
            array("uf" => "AL", "nome" => "MASSARANDUBA"),
            array("uf" => "AL", "nome" => "MATA GRANDE"),
            array("uf" => "AL", "nome" => "MATRIZ DE CAMARAGIBE"),
            array("uf" => "AL", "nome" => "MESSIAS"),
            array("uf" => "AL", "nome" => "MINADOR DO NEGRAO"),
            array("uf" => "AL", "nome" => "MONTEIROPOLIS"),
            array("uf" => "AL", "nome" => "MOREIRA"),
            array("uf" => "AL", "nome" => "MUNGUBA"),
            array("uf" => "AL", "nome" => "MURICI"),
            array("uf" => "AL", "nome" => "NOVO LINO"),
            array("uf" => "AL", "nome" => "OLHO D AGUA GRANDE"),
            array("uf" => "AL", "nome" => "OLHO D AGUA DAS FLORES"),
            array("uf" => "AL", "nome" => "OLHO D AGUA DE CIMA"),
            array("uf" => "AL", "nome" => "OLHO D AGUA DO CASADO"),
            array("uf" => "AL", "nome" => "OLHO D AGUA DOS DANDANHAS"),
            array("uf" => "AL", "nome" => "OLIVENCA"),
            array("uf" => "AL", "nome" => "OURO BRANCO"),
            array("uf" => "AL", "nome" => "PALESTINA"),
            array("uf" => "AL", "nome" => "PALMEIRA DE FORA"),
            array("uf" => "AL", "nome" => "PALMEIRA DOS INDIOS"),
            array("uf" => "AL", "nome" => "PAO DE ACUCAR"),
            array("uf" => "AL", "nome" => "PARICONHA"),
            array("uf" => "AL", "nome" => "PARIPUEIRA"),
            array("uf" => "AL", "nome" => "PASSO DE CAMARAGIBE"),
            array("uf" => "AL", "nome" => "PAU D ARCO"),
            array("uf" => "AL", "nome" => "PAU FERRO"),
            array("uf" => "AL", "nome" => "PAULO JACINTO"),
            array("uf" => "AL", "nome" => "PENEDO"),
            array("uf" => "AL", "nome" => "PIACABUCU"),
            array("uf" => "AL", "nome" => "PILAR"),
            array("uf" => "AL", "nome" => "PINDOBA"),
            array("uf" => "AL", "nome" => "PIRANHAS"),
            array("uf" => "AL", "nome" => "POCAO"),
            array("uf" => "AL", "nome" => "POCO DA PEDRA"),
            array("uf" => "AL", "nome" => "POCO DAS TRINCHEIRAS"),
            array("uf" => "AL", "nome" => "PORTO CALVO"),
            array("uf" => "AL", "nome" => "PORTO DE PEDRAS"),
            array("uf" => "AL", "nome" => "PORTO REAL DO COLEGIO"),
            array("uf" => "AL", "nome" => "POXIM"),
            array("uf" => "AL", "nome" => "QUEBRANGULO"),
            array("uf" => "AL", "nome" => "RIACHO DO SERTAO"),
            array("uf" => "AL", "nome" => "RIACHO FUNDO DE CIMA"),
            array("uf" => "AL", "nome" => "RIO LARGO"),
            array("uf" => "AL", "nome" => "ROCHA CAVALCANTE"),
            array("uf" => "AL", "nome" => "ROTEIRO"),
            array("uf" => "AL", "nome" => "SANTA EFIGENIA"),
            array("uf" => "AL", "nome" => "SANTA LUZIA DO NORTE"),
            array("uf" => "AL", "nome" => "SANTANA DO IPANEMA"),
            array("uf" => "AL", "nome" => "SANTANA DO MUNDAU"),
            array("uf" => "AL", "nome" => "SANTO ANTONIO"),
            array("uf" => "AL", "nome" => "SAO BRAS"),
            array("uf" => "AL", "nome" => "SAO JOSE DA LAJE"),
            array("uf" => "AL", "nome" => "SAO JOSE DA TAPERA"),
            array("uf" => "AL", "nome" => "SAO LUIS DO QUITUNDE"),
            array("uf" => "AL", "nome" => "SAO MIGUEL DOS CAMPOS"),
            array("uf" => "AL", "nome" => "SAO MIGUEL DOS MILAGRES"),
            array("uf" => "AL", "nome" => "SAO SEBASTIAO"),
            array("uf" => "AL", "nome" => "SAPUCAIA"),
            array("uf" => "AL", "nome" => "SAPUCAIA"),
            array("uf" => "AL", "nome" => "SATUBA"),
            array("uf" => "AL", "nome" => "SENADOR RUI PALMEIRA"),
            array("uf" => "AL", "nome" => "SERRA DA MANDIOCA"),
            array("uf" => "AL", "nome" => "SERRA DO SAO JOSE"),
            array("uf" => "AL", "nome" => "TABOLEIRO DO PINTO"),
            array("uf" => "AL", "nome" => "TABOQUINHA"),
            array("uf" => "AL", "nome" => "TANQUE D ARCA"),
            array("uf" => "AL", "nome" => "TAQUARANA"),
            array("uf" => "AL", "nome" => "TATUAMUNHA"),
            array("uf" => "AL", "nome" => "TEOTONIO VILELA"),
            array("uf" => "AL", "nome" => "TRAIPU"),
            array("uf" => "AL", "nome" => "UNIAO DOS PALMARES"),
            array("uf" => "AL", "nome" => "USINA CAMACARI"),
            array("uf" => "AL", "nome" => "VICOSA"),
            array("uf" => "AL", "nome" => "VILA APARECIDA"),
            array("uf" => "AL", "nome" => "VILA SAO FRANCISCO")
        );

     foreach ($ufs as $uf) {
            $this->command->info('Inserindo cidades de '.$uf[0]['uf'].' ['.  count($uf).']..');
            \Artesaos\Cidade::insert($uf);
        }
    }

}
